---

- name: Install nginx
  hosts: instance
  become: true
  tasks:
    - name: update
      apt:
        update_cache: yes

    - name: nginx
      apt:
        name: nginx
        state: latest

    - name: start
      service:
        name: nginx
        state: started

- name: Install node and pm2
  hosts: instance
  become: true
  tasks:
    - name: update
      apt:
        update_cache: yes

    - name: node
      apt:
        name: nodejs
        state: latest

    - name: pm2
      npm:
        global: yes
        name: pm2

- name: Run app
  hosts: instance
  become: true
  tasks:
    - name: pull repo
      git:
        repo: https://github.com/abkunal/Chat-App-using-Socket.io.git
        dest: /home/pablo/Desktop/app

    - name: install packages
      shell: npm install
      args:
        chdir: /home/pablo/Desktop/app

    - name: run app
      become: no
      shell: pm2 start app.js --name "chatapp"
      args:
        chdir: /home/pablo/Desktop/app
